AirHotel/Models/Customer.cs
namespace AirHotel.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        // navigation property
        public virtual List<Order>? Orders { get; set; }
    }
}

AirHotel/Models/Order.cs
namespace AirHotel.Models
{
    public class Order
    {
        public int OrderId { get; set; }
        public string OrderDate { get; set; } = string.Empty;
        public int CustomerId { get; set; }
        // navigation property
        public virtual Customer Customer { set; get; } = default!;
        // navigation property
        public virtual List<OrderItem>? OrderItems{ get; set; }
        public decimal TotalPrice { get; set; }
    }
}

AirHotel/Models/OrderItem.cs
namespace AirHotel.Models
{
    public class OrderItem
    {
        public int OrderItemId { get; set; }
        public int HotelId { get; set; }

        public virtual Hotel Hotel { get; set; }
        public int Quantity { get; set; }
        public int OrderId { get; set; }

        public virtual Order Order { get; set; } = default!;
        public decimal OrderItemPrice {  get; set; }
    }
}

AirHotel/Controllers/CustomerController.cs
using AirHotel.DAL;
using AirHotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirHotel.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IGenericRepository<Customer> _customerRepository;

        public CustomerController(IGenericRepository<Customer> customerRepository)
        {
            _customerRepository = customerRepository;
        }
        public async Task<IActionResult> Table()
        {
            var customers = await _customerRepository.GetAll();
            return View(customers);
        }
    }
}

AirHotel/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using AirHotel.Models;
using AirHotel.ViewModels;
using AirHotel.DAL;
using Microsoft.AspNetCore.Authorization;

namespace AirHotel.Controllers
{
    public class HotelController : Controller
        {

            private readonly IGenericRepository<Hotel> _hotelRepository;

            public HotelController(IGenericRepository<Hotel> hotelRepository)
            {
                _hotelRepository = hotelRepository;
            }

       

            public async Task<IActionResult> Table() {
                var hotels = await _hotelRepository.GetAll();
                var hotelListViewModel = new HotelListViewModel(hotels, "Liste");
                return View(hotelListViewModel); 
            }

            public async Task<IActionResult> Grid() {
            var hotels = await _hotelRepository.GetAll();
                var hotelListViewModel = new HotelListViewModel(hotels, "Grid");
                return View(hotelListViewModel);
            }

            public async Task<IActionResult> Card() {
               var  hotels = await _hotelRepository.GetAll();
            var hotelListViewModel = new HotelListViewModel(hotels, "Card");
                return View(hotelListViewModel);
            }


        public async Task<IActionResult> Details(int id) {
                var hotel = await _hotelRepository.GetEntitylById(id);
   
                if(hotel == null)
                    return BadRequest("Hotel not found");
                return View(hotel);
            }
       

        [HttpGet]
        [Authorize]
        public IActionResult Create(){
                return View();
            }

  

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Hotel hotel)
           {
               if (ModelState.IsValid)
               {
                   await _hotelRepository.Create(hotel);
                   return RedirectToAction(nameof(Card));
               }
               return View(hotel);
           }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Update(int id)
        {
            var item = await _hotelRepository.GetEntitylById(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Update(Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                await _hotelRepository.Update(hotel);
                
                return RedirectToAction(nameof(Card));
            }
            return View(hotel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _hotelRepository.GetEntitylById(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _hotelRepository.Delete(id);
            return RedirectToAction(nameof(Card));
        }


        /*
         public IActionResult Table()
         {
             var hotelListe = GetHotel();
             ViewBag.CurrentViewName = "Liste";
             return View(hotelListe);
         }

         public IActionResult Grid()
         {
             var hotelListe = GetHotel();
             ViewBag.CurrentViewName = "Grid";
             return View(hotelListe);
         }
       

        public List<Hotel> GetHotel()
        {
            var hotelListe = new List<Hotel>(); //lager en liste av type Hotel

            var hotel1 = new Hotel
            {
                HotelId = 1,
                HotelName = "Ali's Hotel",
                Price = 150,
                HotelDescription = "Rett vi Oslo S",
                ImageUrl = "/images/hotel1.jpg"
            };

            var hotel2 = new Hotel
            {
                HotelId = 2,
                HotelName = "JP's Hotel",
                Price = 200,
                HotelDescription = "Rett vi OsloMet",
                ImageUrl = "/images/hotel2.jpg"
            };

            var hotel3 = new Hotel
            {
                HotelId = 3,
                HotelName = "Gisle's Hotel",
                Price = 200,
                HotelDescription = "Rett vi Nasjonal",
                ImageUrl = "/images/hotel3.jpg"
            };

            var hotel4 = new Hotel
            {
                HotelId = 4,
                HotelName = "Olivers's Hotel",
                Price = 400,
                HotelDescription = "Rett vi slottet",
                ImageUrl = "/images/AirRooms/AirRoom1.jpg"
            };

            hotelListe.Add(hotel1);
            hotelListe.Add(hotel2);
            hotelListe.Add(hotel3);
            hotelListe.Add(hotel4);
            return hotelListe;
        }
        */
    }

}

AirHotel/Controllers/OrderController.cs
using AirHotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using AirHotel.ViewModels;
using AirHotel.DAL;
using Microsoft.AspNetCore.Authorization;

namespace AirHotel.Controllers
{
    public class OrderController : Controller
    {
        private readonly IGenericRepository<Order> _orderRepository;
        private readonly IGenericRepository<Hotel> _hotelRepository;
        private readonly IGenericRepository<OrderItem> _orderItemRepository;

        public OrderController(IGenericRepository<Order> orderRepository, IGenericRepository<Hotel> hotelRepository, IGenericRepository<OrderItem> orderItemRepository)
        {
            _orderRepository = orderRepository;
            _hotelRepository = hotelRepository;
            _orderItemRepository = orderItemRepository;
        }
        public async Task<IActionResult> Table()
        {
            var orders = await _orderRepository.GetAll();
            return View(orders);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CreateOrderItem()
        {
            var hotels = await _hotelRepository.GetAll();
            var orders = await _orderRepository.GetAll();
            var createOrderItemViewModel = new CreateOrderItemViewModel
            {
                OrderItem = new OrderItem(),

                ItemSelectList = hotels.Select(item => new SelectListItem
                {
                    Value = item.HotelId.ToString(),
                    Text = item.HotelId.ToString() + ": " + item.HotelName
                }).ToList(),

                OrderSelectList = orders.Select(order => new SelectListItem
                {
                    Value = order.OrderId.ToString(),
                    Text = "Order" + order.OrderId.ToString() + ", Date: " + order.OrderDate + ", Customer: " + order.Customer.Name
                }).ToList(),
            };
            return View(createOrderItemViewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateOrderItem(OrderItem orderItem)
        {
            try
            {
                var newHotel = await _hotelRepository.GetEntitylById(orderItem.HotelId);
                var newOrder = await _orderRepository.GetEntitylById(orderItem.OrderId);

                if (newHotel == null || newOrder == null) {
                    return BadRequest("Item or Order not found");
                }

                var newOrderItem = new OrderItem
                {
                    HotelId = orderItem.HotelId,
                    Hotel = newHotel,
                    Quantity = orderItem.Quantity,
                    OrderId = orderItem.OrderId,
                    Order = newOrder,
                };

                newOrderItem.OrderItemPrice = orderItem.Quantity * newOrderItem.Hotel.Price;

                await _orderItemRepository.Create(newOrderItem);
                return RedirectToAction(nameof(Table));
            }
            catch
            {
                return BadRequest("OrderItem Creation Failed");
            }
        }
    }
}

AirHotel/Views/Shared/_Card.cshtml
@model Hotel

<style>
    .card-img-overlay {
        bottom: auto !important;
    }
</style>

<div class="col-sm-4">
    <div class="card">
        <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.HotelName">
        <div class="card-body">
            <div class="card-img-overlay">
                <h5 class="card-title">
                    <a
                        asp-controller="Hotel"
                        asp-action="Details"
                        asp-route-id="@Model.HotelId">@Model.HotelName
                        </a>
                    </h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">@Model.Price.ToString("0.00 NOK") per natt</h6>

        
            </div>

            <p class="card-text">@Model.HotelDescription</p>

            <div class="button-container">
                <a class="btn btn-primary"
                   asp-controller="Hotel"
                   asp-action="Details"
                   asp-route-id="@Model.HotelId">
                    Reserver
                </a>

                <a class="btn btn-primary"
                   asp-controller="Hotel"
                   asp-action="Update"
                   asp-route-id="@Model.HotelId">
                    Update
                </a>
                <a class="btn btn-primary"
                   asp-controller="Hotel"
                   asp-action="Delete"
                   asp-route-id="@Model.HotelId">
                    Delete
                </a>
            </div>
       
         
        </div>
        <div class="card-footer">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <i class="bi bi-check2-square"></i> A/C
                </li>
                <li class="list-inline-item">
                    <i class="bi bi-check2-square"></i> Garasje
                </li>
                <li class="list-inline-item">
                    <i class="bi bi-check2-square"></i> Pool
                </li>
                <li class="list-inline-item">
                    <i class="bi bi-check2-square"></i> Wifi
                </li>
            </ul>
        </div>
    </div>

</div>

AirHotel/Views/Shared/_Carousel.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="~/images/AirHotel_1.jpg" class="d-block w-100" alt="Oslo S">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="display-4">Welcome to AirHotel</h1>
                <p class="lead">Have fun while traveling</p>
                <button class="btn btn-primary">Book a room</button>
            </div>
        </div>
        <div class="carousel-item active">
            <img src="~/images/AirHotel_2.jpg" class="d-block w-100" alt="Nasjonal">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="display-4">Welcome to AirHotel</h1>
                <p class="lead">Always here to accomidate our guests</p>
                <button class="btn btn-primary">Contact us</button>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/AirHotel_3.jpg" class="d-block w-100" alt="OsloMet">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="display-4">Welcome to AirHotel</h1>
                <p class="lead">Rent out your room in a few clicks</p>
                <button class="btn btn-primary">Register room</button>
            </div>
        </div>
    </div>
</div>

AirHotel/Views/Shared/_CustomerTable.cshtml
@model IEnumerable<Customer>

<div class="container">
    <table class='table table-striped'>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Adress</th>
            <th>Orders</th>
            <th>Action</th>
        </tr>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.CustomerId</td>
                <td>@customer.Name</td>
                <td>@customer.Address</td>
                <td>
                    @if (customer.Orders != null)
                    {
                        <p>@string.Join(",",customer.Orders.Select(order => $"Order{order.OrderId}"))</p>
                    }
                </td>
            </tr>
        }
    </table>
</div>

AirHotel/Views/Shared/_ItemCard.cshtml
@model Hotel

<div class="col">
    <div>
        <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.HotelName">
        <div>
            <div class="d-flex justify-content-between mt-2">
                <h5 class="text-start">
                    <a asp-controller="Hotel"
                       asp-action="Details"
                       asp-route-id="@Model.HotelId">@Model.HotelName</a>
                </h5>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("0.00 NOK")
                </h5>
            </div>
        </div>
    </div>
</div>

AirHotel/Views/Shared/_ItemTable.cshtml
@model IEnumerable<AirHotel.Models.Hotel>

<div class="container">
    <table class='table table-striped'>
        <tr><th>Id</th><th>Name</th><th>Price</th><th>Description</th></tr>
        @foreach (var hotel in Model)
        {
            <tr>
                <td>@hotel.HotelId</td>
                <td>
                    <a asp-controller="Hotel"
                       asp-action="Details"
                       asp-route-id="@hotel.HotelId">@hotel.HotelName</a>
                </td>
                <td>@hotel.Price.ToString("0.00 NOK")</td>
                <td>@hotel.HotelDescription</td>
                <td></td>
            </tr>
        }
    </table>
</div>

AirHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>

    <style>
        /* Her skriver du din CSS-kode */
        .button-container {
            display: flex;
            gap: 10px;
        }
    </style>
</head>
<body>
    
    <header>
        <!-- Grid Oversikt
        <div class="container-fluid">
            <div class="row">
                <div class="col-1" style="background-color:red">1</div>
                <div class="col-1" style="background-color:red">2</div>
                <div class="col-1" style="background-color:red">3</div>
                <div class="col-1" style="background-color:red">4</div>
                <div class="col-1" style="background-color:red">5</div>
                <div class="col-1" style="background-color:red">6</div>
                <div class="col-1" style="background-color:red">7</div>
                <div class="col-1" style="background-color:red">8</div>
                <div class="col-1" style="background-color:red">9</div>
                <div class="col-1" style="background-color:red">10</div>
                <div class="col-1" style="background-color:red">11</div>
                <div class="col-1" style="background-color:red">12</div>
            </div>

        </div>
        -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AirHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Card">Hotels</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Create">Register Hotel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Table">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Table">Orders</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <main role="main" class="pb-3">
        @RenderBody()
        @RenderSection("scripts", required: false)
    </main>


    <!--Footer-->

    <footer class="p-5 bg-dark text-white text-center position-relative">
        <div class="container">
            <p class="lead">Copyright</p>
        </div>
    </footer>
</body>


</html>

AirHotel/Views/Shared/_OrderItemTable.cshtml
@model IEnumerable<OrderItem>

<div class="container">
    <table class='table table-striped' style='max-width: 1200px;'>
        <tr>
            <th>OrderItemId</th>
            <th>HotelId</th>
            <th>Hotel</th>
            <th>Total days</th>
            <th>Total Amount</th>
            <th>Actions</th>
        </tr>
        @foreach (var orderItem in Model)
        {
            <tr>
                <td>@orderItem.OrderItemId</td>
                <td>@orderItem.HotelId</td>
                <td>@orderItem.Hotel.HotelName</td>
                <td>@orderItem.Quantity</td>
                <td>@orderItem.OrderItemPrice</td>
                <td></td>
            </tr>
        }
    </table>
</div>

AirHotel/Views/Shared/_Orders.cshtml
@model IEnumerable<Order>

@foreach (var order in Model)
{
    <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
        <div class="container">
            <h5>Order @order.OrderId </h5>
            <div>
                <table class='table table-striped' style='max-width: 1200px;'>
                    <tr class="table-header">
                        <th>Order Date</th>
                        <th>CustomerId</th>
                        <th>Customer Name</th>
                        <th>Address</th>
                    </tr>
                    <tr>
                        <td>@order.OrderDate</td>
                        <td>@order.CustomerId</td>
                        <td>@order.Customer.Name</td>
                        <td>@order.Customer.Address</td>
                    </tr>
                </table>
            </div>
        </div>
        <partial name="_OrderItemTable" model="order.OrderItems" />
    </div>
}